-- Inser��es para a tabela users
INSERT INTO users (login, password, role, grupo_id) VALUES ('tdouglas', 'er8%6fAoN@', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('denisenorris', '2ajLBJGn+3', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('morgan03', 'bF89+Eub9%', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('michellemccall', 'g4Fl4GG2)N', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('parsonserin', 'J$0oNwJfd%', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('leegrant', '()XOoHXde6', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('jthomas', 'I$9Es6suA#', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('leah22', '70vST5la$2', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('turnerdonald', 'PF&7@2UjOx', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('catherine54', '^2otQzi0gP', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('malonechristie', '@#12RJGa5q', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ehernandez', '4p^4F%Etn^', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ramosdaryl', '_VE4aKg*t+', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('allencharles', 'P(9Cjwu+@s', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ckelly', '!5GKgMfyHc', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('dan07', '$4MPC*u%kI', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('michaelfowler', 'N+26XGroYi', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('hernandezdon', 'op3l3POa!0', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('carrie15', 'l&o5Tn%Vu@', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('thomaswalker', 'snyL5LwdH(', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('autumn14', '(2wXP7$vLk', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('jeremiah26', 'b0s8Uz8j$u', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('torresthomas', ')4@l5Je$po', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('luisfrank', '^1^Gr#mM9g', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('justinruiz', 'Gk7C2Qmn+)', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('charlesreyes', 'i!32_Abh)*', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ujoseph', '$5YiZYqn1h', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('lmoody', '!T)%9DEuXd', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ishaw', 'EFA)4Zphdw', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('aorozco', 'wUOh2d)oc_', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('wilsoncynthia', 'dDGxwaLm$3', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('scottclarke', '!4@TUuwB!S', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('zsmith', '73N&bZwU%A', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('rodneyturner', 'x1mRhXpa!_', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('brendancasey', 'z1vs*GGyn$', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('lauren09', '(oZJ6JMiq0', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('blarson', '#6o8OmlJNG', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('alvarezmicheal', '$KU4ILea+8', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('christinejacobs', '*X#Un8Izbh', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('mitchellwillie', 'jh0e1Tr7%J', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('osexton', '!zX2vOMq2L', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('jacksondonald', '#rATaW*m58', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('spencercarrillo', '%@B6dOt+Py', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('camachoheather', 'RDNm1OpDj(', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ericpowell', '&3iMOel95)', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('dthompson', '_@joS2EzWG', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('perryjustin', 'K05WhTJHJ!', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('melissa57', '6*59UiQsfE', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('jimmcpherson', '$03VVsBoj&', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('kking', '&XEI!hf%x0', 'Admin', 1);

-- Inser��es para a tabela config_Indicador
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('expert', 'court', '=', '25', 'beyond', 'hair', '>', '72', 'davisnatalie', 'Generation present class here wife west yes perhaps serious site lead.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('enter', 'hit', '>', '79', 'would', 'glass', '>=', '13', 'paulawoods', 'Whether popular available career small science.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('ball', 'writer', '<', '32', 'move', 'nearly', '<=', '72', 'ijohnson', 'Cultural agree TV town this too compare financial strategy low last fast.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('others', 'war', '>=', '50', 'pass', 'move', '>=', '46', 'bbennett', 'Third yet treat international knowledge science meeting many truth sometimes discover reason.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('course', 'current', '=', '31', 'everybody', 'ball', '>=', '80', 'bjones', 'Room Congress business scene local on star.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('shoulder', 'let', '>=', '14', 'grow', 'accept', '>', '82', 'fdavis', 'Already simple hard choose free friend another culture hospital.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('tend', 'true', '<', '81', 'might', 'as', '<=', '96', 'patelronald', 'Offer much drive by somebody fact sound space state doctor up.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('including', 'hard', '<', '38', 'little', 'activity', '<', '48', 'rbennett', 'Table involve protect and region wish use financial open reduce easy Mr.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('skill', 'value', '<=', '22', 'determine', 'six', '=', '79', 'robert47', 'Room candidate with art past environmental white apply money.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('herself', 'value', '>', '13', 'hot', 'thank', '>', '38', 'williamlee', 'Respond expert people any get traditional bill gas standard student age wish American.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('authority', 'story', '>=', '97', 'her', 'person', '>', '35', 'uhuang', 'Happen beat away increase maintain party reveal.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('area', 'six', '<', '23', 'difficult', 'during', '<', '27', 'brenda72', 'Enjoy card base stay culture purpose stuff really.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('peace', 'amount', '<=', '38', 'race', 'foot', '<', '57', 'michaellewis', 'Amount popular add manage require quickly certain coach or art.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('degree', 'surface', '>=', '53', 'around', 'do', '>=', '73', 'christopher78', 'Despite station address door alone keep.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('image', 'although', '=', '38', 'piece', 'war', '<', '46', 'ricky02', 'Agency trouble short huge every range.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('kitchen', 'more', '<', '65', 'five', 'wrong', '<', '6', 'sarahchavez', 'Skin me most hear yourself land culture pass show great black.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('race', 'may', '=', '15', 'perform', 'dream', '<=', '40', 'carrie26', 'Leg establish put available support still state bag.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('certainly', 'somebody', '<=', '49', 'yes', 'perform', '<=', '42', 'patriciawagner', 'Country expect toward me small specific all nice.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('family', 'Mrs', '<', '73', 'themselves', 'small', '>=', '59', 'camposgordon', 'School painting leave budget century loss carry sort audience.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('catch', 'debate', '>', '37', 'president', 'bring', '>=', '72', 'vincent42', 'Fill whether now evidence truth themselves week effect performance recently beyond.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('air', 'move', '<=', '89', 'minute', 'me', '>', '55', 'hernandeztravis', 'Now democratic produce edge impact program security along any wind.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('build', 'ahead', '=', '90', 'truth', 'response', '>', '82', 'slane', 'There decade guess garden central memory these mean peace news agent read.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('opportunity', 'security', '<', '52', 'information', 'grow', '>=', '60', 'myersdavid', 'Believe face before him season particular painting role cut opportunity most all interview.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('the', 'discussion', '>=', '30', 'growth', 'natural', '>=', '13', 'linpeter', 'Local produce nice view receive nothing international order expert.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('near', 'key', '=', '32', 'decade', 'simple', '=', '53', 'qcollier', 'Finally assume size two for focus meeting process.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('practice', 'company', '<=', '23', 'see', 'election', '>=', '26', 'ashleytucker', 'Population effort detail car major month develop money establish military around across message.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('scientist', 'pretty', '>', '5', 'knowledge', 'doctor', '<', '42', 'robert25', 'Game know old against decide technology group be gun for reflect series.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('structure', 'get', '>', '17', 'everything', 'night', '>', '58', 'qkennedy', 'Into must many want clearly impact number enjoy unit run take relationship also.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('hour', 'training', '<=', '6', 'laugh', 'machine', '>', '51', 'wcarroll', 'Skill pull seat follow suddenly because government even necessary lawyer.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('event', 'most', '>=', '45', 'remain', 'step', '<', '10', 'brianyoung', 'Federal share modern top can ball story serve life.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('attorney', 'mission', '>', '67', 'week', 'nothing', '<', '71', 'christopher84', 'Rather employee nearly cultural ok artist through education police.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('unit', 'he', '>=', '57', 'wife', 'yet', '<=', '90', 'megankoch', 'Safe when if success wonder ago international a meeting.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('crime', 'thus', '>', '84', 'sit', 'although', '>', '68', 'millerpatrick', 'Maintain protect will interview tax industry land evening.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('establish', 'maybe', '>', '37', 'seat', 'environment', '>=', '58', 'pauljones', 'No thousand place voice group far lose at.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('her', 'respond', '=', '80', 'face', 'quickly', '>', '60', 'samantha69', 'Result so but shake music case author five open.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('sign', 'wait', '<=', '65', 'natural', 'cold', '>=', '100', 'anthonysmith', 'They I live now player left front poor drive.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('half', 'nothing', '<', '79', 'put', 'positive', '<=', '55', 'rileymckenzie', 'Drop spring blood positive church how lay free baby lot media.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('every', 'hope', '>=', '41', 'design', 'without', '>', '75', 'seanhowell', 'Radio less collection laugh figure picture imagine up short guess organization score.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('north', 'full', '<=', '82', 'contain', 'especially', '=', '71', 'arichardson', 'Describe group discuss against maintain speech.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('real', 'ability', '>=', '43', 'into', 'admit', '>=', '44', 'omatthews', 'Car large strategy statement no information total strategy court soon professor forget.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('concern', 'early', '<=', '4', 'quite', 'model', '>', '13', 'aellis', 'Real entire as give language national mission tonight establish reveal system eye find.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('look', 'finally', '>=', '49', 'campaign', 'live', '<=', '50', 'gardnerlevi', 'Positive degree wind action home week outside.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('security', 'chair', '<', '5', 'fine', 'others', '>=', '99', 'bonnie19', 'Experience until right really for toward necessary sort develop thank.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('interest', 'deal', '=', '36', 'stay', 'yeah', '<', '46', 'christophermorris', 'Live service practice tree action thing rest assume score.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('two', 'field', '=', '38', 'reality', 'myself', '>=', '92', 'johnnyperez', 'Kind field coach side hand whose news teach.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('despite', 'toward', '>', '62', 'state', 'third', '<', '26', 'lydiaenglish', 'Region international what of with strategy most.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('scene', 'appear', '=', '99', 'allow', 'rich', '=', '53', 'tyler91', 'Put doctor decade change north during return billion night matter.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('available', 'whether', '<=', '49', 'item', 'reason', '<', '31', 'kmiller', 'Music discover foreign reality experience cultural like during.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('bank', 'forget', '<=', '59', 'guess', 'sign', '>=', '9', 'johnsonsamantha', 'Pull treatment help stay student animal carry well as why order message.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('accept', 'gun', '>', '45', 'own', 'middle', '=', '64', 'ftaylor', 'Technology season future north fear meet cold country party.');

-- Inser��es para a tabela dim_acao_seletiva
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (1, 'Tipo C', '2024-02-18');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (2, 'Tipo B', '2024-10-19');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (3, 'Tipo A', '2024-06-08');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (4, 'Tipo A', '2024-05-31');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (5, 'Tipo C', '2024-04-05');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (6, 'Tipo B', '2024-03-20');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (7, 'Tipo A', '2024-07-02');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (8, 'Tipo C', '2024-06-29');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (9, 'Tipo B', '2024-04-26');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (10, 'Tipo C', '2024-06-13');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (11, 'Tipo B', '2024-01-16');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (12, 'Tipo B', '2024-10-29');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (13, 'Tipo A', '2024-04-07');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (14, 'Tipo C', '2024-11-20');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (15, 'Tipo A', '2024-05-23');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (16, 'Tipo B', '2024-08-11');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (17, 'Tipo C', '2024-10-19');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (18, 'Tipo A', '2024-03-18');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (19, 'Tipo C', '2024-09-30');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (20, 'Tipo C', '2024-07-24');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (21, 'Tipo C', '2024-01-16');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (22, 'Tipo C', '2024-05-04');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (23, 'Tipo B', '2024-03-30');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (24, 'Tipo B', '2024-03-28');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (25, 'Tipo C', '2024-03-24');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (26, 'Tipo C', '2024-04-25');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (27, 'Tipo C', '2024-10-06');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (28, 'Tipo A', '2024-08-09');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (29, 'Tipo B', '2024-05-16');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (30, 'Tipo C', '2024-01-29');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (31, 'Tipo B', '2024-01-20');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (32, 'Tipo C', '2024-04-19');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (33, 'Tipo A', '2024-09-13');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (34, 'Tipo C', '2024-03-21');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (35, 'Tipo B', '2024-07-07');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (36, 'Tipo A', '2024-06-07');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (37, 'Tipo B', '2024-05-27');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (38, 'Tipo C', '2024-06-01');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (39, 'Tipo C', '2024-10-26');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (40, 'Tipo B', '2024-06-09');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (41, 'Tipo A', '2024-01-04');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (42, 'Tipo C', '2024-05-31');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (43, 'Tipo A', '2024-07-12');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (44, 'Tipo A', '2024-03-12');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (45, 'Tipo B', '2024-08-05');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (46, 'Tipo A', '2024-07-25');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (47, 'Tipo B', '2024-06-10');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (48, 'Tipo C', '2024-06-01');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (49, 'Tipo C', '2024-01-19');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (50, 'Tipo A', '2024-10-27');

-- Inser��es para a tabela dim_contratacao
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (1, '2024-03-20', 7944.04, 1, '2024-08-22');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (2, '2024-05-25', 12321.8, 1, '2024-08-15');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (3, '2024-03-09', 9471.09, 1, '2024-07-14');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (4, '2024-01-26', 9514.81, 1, '2024-01-23');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (5, '2024-08-04', 12643.88, 3, '2024-01-28');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (6, '2024-09-30', 3959.23, 2, '2024-10-16');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (7, '2024-04-13', 3272.58, 3, '2024-11-04');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (8, '2024-03-02', 4122.24, 3, '2024-08-26');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (9, '2024-03-29', 13845.26, 2, '2024-07-26');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (10, '2024-04-16', 7677.26, 1, '2024-08-14');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (11, '2024-02-26', 13380.65, 1, '2024-10-16');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (12, '2024-10-07', 8882.27, 3, '2024-05-17');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (13, '2024-07-18', 13740.45, 2, '2024-01-10');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (14, '2024-03-14', 3430.77, 2, '2024-10-11');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (15, '2024-07-15', 6252.98, 2, '2024-03-25');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (16, '2024-06-16', 13843.53, 3, '2024-03-07');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (17, '2024-11-02', 5554.47, 3, '2024-10-23');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (18, '2024-07-03', 8828.08, 2, '2024-05-04');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (19, '2024-05-30', 10669.31, 1, '2024-02-12');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (20, '2024-03-02', 9981.33, 3, '2024-07-19');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (21, '2024-03-16', 14858.12, 2, '2024-03-20');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (22, '2024-10-08', 7126.73, 2, '2024-06-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (23, '2024-05-29', 10259.57, 2, '2024-10-25');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (24, '2024-11-08', 8531.55, 2, '2024-07-23');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (25, '2024-03-07', 7468.57, 3, '2024-04-23');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (26, '2024-01-11', 6844.3, 3, '2024-05-16');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (27, '2024-04-19', 3912.36, 3, '2024-07-05');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (28, '2024-01-27', 13171.17, 2, '2024-02-14');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (29, '2024-07-20', 4687.04, 3, '2024-03-15');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (30, '2024-03-16', 11619.98, 1, '2024-02-16');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (31, '2024-10-09', 14883.29, 1, '2024-04-21');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (32, '2024-04-13', 10800.48, 3, '2024-04-14');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (33, '2024-10-14', 7096.5, 2, '2024-07-20');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (34, '2024-09-24', 7240.33, 3, '2024-05-25');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (35, '2024-07-15', 11582.66, 1, '2024-01-09');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (36, '2024-10-06', 10649.96, 1, '2024-07-27');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (37, '2024-05-10', 6017.02, 1, '2024-11-07');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (38, '2024-08-20', 14176.86, 3, '2024-08-29');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (39, '2024-08-05', 10048.3, 2, '2024-10-25');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (40, '2024-06-16', 3694.53, 1, '2024-09-16');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (41, '2024-03-06', 5823.0, 3, '2024-07-05');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (42, '2024-06-04', 10545.85, 1, '2024-05-22');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (43, '2024-04-28', 13734.89, 3, '2024-03-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (44, '2024-10-27', 11896.29, 1, '2024-09-19');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (45, '2024-09-02', 12848.89, 1, '2024-11-12');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (46, '2024-07-14', 11315.37, 2, '2024-08-30');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (47, '2024-06-25', 6146.37, 3, '2024-11-15');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (48, '2024-08-01', 10394.54, 1, '2024-10-23');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (49, '2024-08-17', 6172.71, 3, '2024-04-02');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (50, '2024-06-08', 9972.03, 3, '2024-10-12');

-- Inser��es para a tabela dim_entrevista
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (1, '2024-09-04', 'Kelly Dudley', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (2, '2024-04-10', 'Nathan Hines', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (3, '2024-03-03', 'Maria Ho', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (4, '2024-08-04', 'Dean Jones', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (5, '2024-03-20', 'Tammy Hall', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (6, '2024-06-09', 'Micheal Murphy', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (7, '2024-07-29', 'Gabriela Mendoza DVM', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (8, '2024-01-13', 'Zachary Berry', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (9, '2024-05-08', 'Julie Zimmerman', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (10, '2024-09-20', 'Alicia Castro', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (11, '2024-08-10', 'Kimberly Oliver', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (12, '2024-09-29', 'Megan Krueger', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (13, '2024-09-25', 'Todd Arroyo', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (14, '2024-05-10', 'Brooke Roberts', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (15, '2024-10-22', 'Jamie Lawrence', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (16, '2024-08-11', 'Robin Long', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (17, '2024-09-12', 'Ralph Morgan', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (18, '2024-05-04', 'Lisa Hicks', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (19, '2024-03-04', 'Jessica Soto', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (20, '2024-11-14', 'Peter Horton DVM', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (21, '2024-01-03', 'Mr. Jeffrey Gonzalez Jr.', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (22, '2024-07-31', 'Gary Kirk', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (23, '2024-11-14', 'Michael Jackson', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (24, '2024-01-31', 'James Webb', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (25, '2024-04-09', 'Kristin Holder', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (26, '2024-07-30', 'John Cervantes', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (27, '2024-05-13', 'Marisa Hoover', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (28, '2024-04-15', 'Jack Estrada', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (29, '2024-05-04', 'Daniel Moody', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (30, '2024-05-20', 'Micheal Clark', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (31, '2024-07-16', 'Joshua Reese', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (32, '2024-03-17', 'Arthur Torres', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (33, '2024-02-04', 'Dr. Susan Meyer', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (34, '2024-04-25', 'Andrea Taylor', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (35, '2024-02-09', 'Timothy Reyes', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (36, '2024-10-13', 'Jose Coffey', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (37, '2024-09-14', 'Theodore Noble', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (38, '2024-05-18', 'Matthew Williams', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (39, '2024-02-03', 'Stephanie Christian', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (40, '2024-02-15', 'Andrea Mills', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (41, '2024-05-29', 'Kent Knapp', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (42, '2024-08-04', 'Jennifer Gonzalez', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (43, '2024-01-27', 'Craig Gay', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (44, '2024-06-15', 'Robert Ross', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (45, '2024-04-19', 'Paula Morrison', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (46, '2024-09-09', 'Hunter Stevens', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (47, '2024-02-06', 'Alison Baldwin', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (48, '2024-04-15', 'James Barajas', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (49, '2024-08-14', 'Antonio Maldonado', 'Em an�lise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (50, '2024-01-18', 'Brandon Cummings', 'Reprovado');

-- Inser��es para a tabela dim_feedback
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (1, 'Century adult professor building performance first treatment price goal apply morning.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (2, 'Born moment several center measure because include concern man off high.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (3, 'Today science current media green everyone risk.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (4, 'Concern sort ahead soldier campaign base business indicate.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (5, 'Street tell provide grow class like.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (6, 'Big example appear economy especially civil like Mrs scientist lawyer wonder.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (7, 'Section then mother manager cause fact job majority statement notice owner decade require baby.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (8, 'Debate peace perform use time image professor identify garden hotel produce.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (9, 'Back charge away head first culture hospital.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (10, 'Space few care loss sound long eye avoid.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (11, 'Support which affect buy mission late draw fear light young Mr.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (12, 'Different affect memory well behavior better woman idea choose get political.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (13, 'Foreign piece same red everything life.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (14, 'Large adult million ten property place challenge to should.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (15, 'Public inside heavy find story star.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (16, 'Public something large continue act score hair.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (17, 'Able impact president onto involve team military.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (18, 'Before myself last true hold surface between.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (19, 'Any my effect share amount put.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (20, 'Every your information doctor exist current store federal half.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (21, 'Wrong since research off concern get.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (22, 'Toward employee art hospital find receive cold before field wish without list.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (23, 'Why various film decision inside performance left bag second score spring away tree.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (24, 'Talk stock business theory charge you almost south realize whether.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (25, 'Kind child recognize get hot always rich bed south his simply crime eat us.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (26, 'Also history democratic career former level sing you represent audience.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (27, 'Fire cell baby member certain identify toward across quickly customer great thus.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (28, 'Because respond but heavy person performance whatever other charge carry perhaps five.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (29, 'Production in final store century real war.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (30, 'Why leave should compare small especially upon town without.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (31, 'Ever need operation exactly Congress data trial military big garden.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (32, 'Radio happen arm talk edge campaign.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (33, 'Hear continue police still organization describe next.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (34, 'Capital parent outside ball management simply once.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (35, 'Traditional impact training agency like serve many nor management particular heavy no.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (36, 'Different second quickly although play maintain let raise woman.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (37, 'Top surface central figure expert threat without moment culture notice hour.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (38, 'Product pick night represent word bag.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (39, 'Back board condition bad find type necessary.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (40, 'Like Republican spring accept someone of all forget less hand year turn.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (41, 'Fear state change beyond part hear ask remember the.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (42, 'Leg night job determine team this I.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (43, 'But image much look eye medical after however brother.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (44, 'Yes down likely member child probably those buy friend chance table.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (45, 'Black bring choose whole player onto history direction enter room commercial.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (46, 'On money country receive card dinner.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (47, 'Peace place present might industry improve middle seven.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (48, 'Vote whether speech dinner me man south instead two expect writer.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (49, 'Able third identify win friend despite role.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (50, 'Past control bill heart stock social shoulder full firm series.');

-- Inser��es para a tabela dim_participante_rh
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (1, 'Laura Knight', 'Horticulturist, amenity');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (2, 'Gregory Williams', 'Fitness centre manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (3, 'Steven Mckenzie', 'Chief Financial Officer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (4, 'Diana Roberts', 'Medical sales representative');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (5, 'Becky Perez', 'Landscape architect');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (6, 'Robert Rice', 'Buyer, industrial');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (7, 'Amy Anderson', 'Tax adviser');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (8, 'Eric Flowers', 'Television/film/video producer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (9, 'Joseph Patel', 'Designer, textile');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (10, 'Anna Taylor', 'Editor, film/video');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (11, 'Daniel Lester MD', 'Runner, broadcasting/film/video');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (12, 'Stephen Kim', 'Garment/textile technologist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (13, 'Michael Hogan', 'Operational researcher');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (14, 'John Conner Jr.', 'Glass blower/designer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (15, 'Richard Gonzales', 'Editor, magazine features');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (16, 'Raymond Martinez', 'Surveyor, planning and development');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (17, 'Cynthia Miller', 'Surveyor, quantity');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (18, 'Theresa Pierce DDS', 'Tour manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (19, 'Ronald Torres', 'Chartered certified accountant');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (20, 'James Spence', 'Sports coach');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (21, 'Jim Roberts', 'Counselling psychologist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (22, 'Xavier Potter', 'Records manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (23, 'Cindy Berg', 'Chief Financial Officer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (24, 'Carrie Lewis', 'Higher education lecturer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (25, 'Michael Harvey', 'Chief Technology Officer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (26, 'Roy Medina', 'Broadcast engineer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (27, 'Jason Allen', 'Geophysicist/field seismologist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (28, 'Lisa Adams', 'Restaurant manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (29, 'Teresa Butler', 'Accountant, chartered management');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (30, 'Carlos May', 'Stage manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (31, 'Eric Williams', 'Production manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (32, 'Shannon Lee', 'Exhibitions officer, museum/gallery');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (33, 'Teresa Lucas', 'Engineer, electrical');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (34, 'Catherine Walter', 'Advertising account planner');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (35, 'Sarah Ross', 'Investment banker, corporate');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (36, 'Jimmy Preston', 'Art therapist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (37, 'James Blake', 'Engineer, civil (consulting)');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (38, 'Crystal Huffman', 'Engineer, energy');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (39, 'Amber Burgess', 'Psychologist, clinical');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (40, 'Krista Ward', 'Editor, magazine features');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (41, 'Daniel Schroeder', 'Furniture designer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (42, 'William Leon', 'Horticulturist, commercial');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (43, 'Lauren Johnson', 'Archaeologist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (44, 'Samuel Mendez', 'Surveyor, planning and development');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (45, 'Vincent Bowen', 'Environmental health practitioner');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (46, 'Kathryn Allen', 'Accountant, chartered certified');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (47, 'Cole Lee', 'Chartered legal executive (England and Wales)');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (48, 'Tina Mendez', 'Solicitor');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (49, 'John Rogers', 'Training and development officer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (50, 'Jennifer Robertson', 'Counsellor');

-- Inser��es para a tabela dim_periodo
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (1, '2024-02-01', '2024-06-12');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (2, '2024-01-15', '2024-05-28');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (3, '2024-05-17', '2024-08-11');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (4, '2024-11-20', '2024-02-18');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (5, '2024-09-06', '2024-03-22');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (6, '2024-02-19', '2024-05-14');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (7, '2024-11-03', '2024-07-20');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (8, '2024-06-12', '2024-02-18');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (9, '2024-10-19', '2024-04-17');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (10, '2024-03-06', '2024-07-20');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (11, '2024-05-21', '2024-10-20');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (12, '2024-05-07', '2024-09-14');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (13, '2024-08-23', '2024-03-19');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (14, '2024-11-11', '2024-09-28');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (15, '2024-08-02', '2024-05-27');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (16, '2024-05-10', '2024-11-16');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (17, '2024-09-09', '2024-06-07');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (18, '2024-02-06', '2024-08-06');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (19, '2024-10-27', '2024-12-05');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (20, '2024-11-09', '2024-10-30');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (21, '2024-08-08', '2024-04-30');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (22, '2024-05-20', '2024-02-01');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (23, '2024-07-01', '2024-03-26');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (24, '2024-06-20', '2024-04-07');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (25, '2024-11-19', '2024-09-12');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (26, '2024-03-31', '2024-11-04');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (27, '2024-03-25', '2024-02-13');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (28, '2024-10-21', '2024-04-23');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (29, '2024-04-22', '2024-02-25');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (30, '2024-10-18', '2024-05-14');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (31, '2024-10-12', '2024-01-25');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (32, '2024-11-21', '2024-02-21');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (33, '2024-08-21', '2024-09-20');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (34, '2024-06-15', '2024-08-28');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (35, '2024-04-26', '2024-06-22');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (36, '2024-04-14', '2024-11-05');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (37, '2024-07-19', '2024-08-16');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (38, '2024-09-08', '2024-07-23');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (39, '2024-05-21', '2024-06-18');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (40, '2024-03-22', '2024-02-24');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (41, '2024-07-21', '2024-09-12');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (42, '2024-03-22', '2024-09-30');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (43, '2024-01-11', '2024-08-03');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (44, '2024-01-21', '2024-09-14');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (45, '2024-01-26', '2024-05-22');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (46, '2024-06-24', '2024-07-22');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (47, '2024-09-28', '2024-06-14');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (48, '2024-08-28', '2024-05-21');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (49, '2024-02-27', '2024-10-20');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (50, '2024-06-09', '2024-06-12');

-- Inser��es para a tabela dim_processo_seletivo
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (1, 'wife', '2024-06-10', '2024-11-06', 'Ativo', 'Danielle Jones', 'Cut away reality sell sport challenge trouble. Democratic full truth easy specific street language.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (2, 'college', '2024-07-05', '2024-08-16', 'Conclu�do', 'Daisy Brown', 'Party though onto write two peace especially whom. Feeling crime pattern goal hold.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (3, 'score', '2024-06-14', '2024-11-01', 'Inativo', 'Yvette Kelley', 'Over drive government order seem quickly. Character dark produce particular we.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (4, 'rest', '2024-06-26', '2024-03-30', 'Inativo', 'Sarah Herrera', 'War without age accept. Clearly administration ground woman movement parent.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (5, 'poor', '2024-02-22', '2024-06-03', 'Inativo', 'Jeffery Robinson', 'Natural allow tend court. Charge reflect guess. Another pull everybody us tough factor.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (6, 'song', '2024-04-11', '2024-04-06', 'Inativo', 'Kenneth Smith', 'Return write personal speak. Above effort each throw piece see book.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (7, 'along', '2024-04-03', '2024-09-11', 'Conclu�do', 'Ashley Ayala', 'Tonight whether detail hard size way you. Live professor section contain.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (8, 'according', '2024-08-22', '2024-06-28', 'Ativo', 'Patricia Reeves', 'Seat particularly speak offer. Success nice but state.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (9, 'drug', '2024-09-11', '2024-06-05', 'Conclu�do', 'Rhonda Harris', 'To feel medical particularly government perform.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (10, 'against', '2024-03-06', '2024-11-30', 'Conclu�do', 'Aaron Campbell', 'Vote already history happen image fly author.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (11, 'enough', '2024-03-19', '2024-07-04', 'Inativo', 'Reginald Ellis', 'Hand whatever figure discuss full organization. Drug look where generation. Present if great score.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (12, 'consider', '2024-03-05', '2024-06-21', 'Inativo', 'Jessica Newton', 'Appear lawyer how go middle growth. Trial perhaps suffer trouble benefit must.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (13, 'film', '2024-10-12', '2024-11-01', 'Conclu�do', 'Louis Butler', 'Game these behavior teach responsibility good. Name out success. Occur word fill leader least.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (14, 'employee', '2024-10-05', '2024-06-21', 'Ativo', 'Tyler Robinson', 'Most per sit sister pressure. Enough skill treat special tell.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (15, 'seat', '2024-07-21', '2024-10-28', 'Conclu�do', 'Ashley Newton', 'Exist identify program culture agreement. Despite see message now fish under she.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (16, 'yeah', '2024-11-12', '2024-02-02', 'Conclu�do', 'Jeremiah Rose', 'Produce friend main believe meeting. Everyone song apply look institution heavy serious.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (17, 'time', '2024-02-13', '2024-10-20', 'Ativo', 'Andrew Vincent', 'Four current around civil responsibility. Vote style factor born argue analysis.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (18, 'develop', '2024-03-04', '2024-07-28', 'Inativo', 'Allen White', 'Head actually sort act green form series. Past decade also fire experience little especially.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (19, 'decision', '2024-09-14', '2024-06-24', 'Inativo', 'Susan Good', 'Per throughout skill blue before peace next. Management office save gun material.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (20, 'according', '2024-09-22', '2024-07-25', 'Inativo', 'Courtney Wilson', 'Serve magazine serve water rise notice play. Itself ask whether begin than culture.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (21, 'most', '2024-06-29', '2024-10-15', 'Inativo', 'John Snyder', 'Parent cover later. Training building there we sort.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (22, 'new', '2024-08-22', '2024-07-31', 'Inativo', 'Aaron Cook', 'There help national debate. Nor station choice letter enjoy first main.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (23, 'summer', '2024-02-08', '2024-06-13', 'Conclu�do', 'Robert Reyes', 'Candidate take memory whatever. Tell decision second late. Three ability almost require support.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (24, 'parent', '2024-08-17', '2024-09-04', 'Conclu�do', 'Jesus Thomas', 'May point particular question win. Son question central chance blood discover tax.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (25, 'control', '2024-11-13', '2024-05-04', 'Ativo', 'Sabrina Hicks', 'Positive century western world pass series.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (26, 'serious', '2024-05-16', '2024-11-14', 'Conclu�do', 'Mr. Robert Mendez MD', 'Maybe ball likely couple.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (27, 'assume', '2024-06-10', '2024-03-20', 'Conclu�do', 'Christopher Mcconnell', 'Rock line write one rich. Consider build about region ten very. There save major.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (28, 'sport', '2024-04-02', '2024-04-01', 'Inativo', 'Kristen Cooper', 'Business nothing out during then bank. Positive trouble development compare.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (29, 'list', '2024-01-20', '2024-09-05', 'Inativo', 'Matthew Dixon', 'Court one prepare here shake.
Analysis how decade method man. Mouth PM occur take very.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (30, 'keep', '2024-08-29', '2024-08-04', 'Conclu�do', 'Danielle Rojas', 'Hope development while prepare street behind.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (31, 'bit', '2024-05-08', '2024-05-21', 'Conclu�do', 'Pamela Shah', 'Consumer carry data read partner guy me. Generation once race pass than account.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (32, 'poor', '2024-08-05', '2024-11-07', 'Conclu�do', 'Crystal Townsend', 'Trade seat similar without feeling evidence. Cup perform still thank contain.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (33, 'forget', '2024-09-24', '2024-11-24', 'Inativo', 'Sheri Rice', 'Computer decade memory west. Budget successful professor see reflect.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (34, 'set', '2024-07-05', '2024-10-15', 'Conclu�do', 'John Watkins', 'Fast use play. Leave thought address maybe hospital whatever life.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (35, 'long', '2024-05-19', '2024-09-10', 'Ativo', 'Sean Thomas', 'Her or husband chair also street. Speech him pay begin. Party account family accept music data.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (36, 'help', '2024-02-24', '2024-10-25', 'Conclu�do', 'Kevin Johnson', 'Whether resource watch develop. Carry program decision firm war every.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (37, 'above', '2024-03-17', '2024-03-02', 'Ativo', 'Michael Poole', 'Address run sort such respond drop. Air per position of seek like.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (38, 'new', '2024-08-24', '2024-06-15', 'Conclu�do', 'Jose Kennedy', 'Like side product. Minute deep future member.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (39, 'seven', '2024-07-26', '2024-06-24', 'Ativo', 'Theodore Curtis', 'Make bar movement account fill wind. Guy defense enough of can. Of appear green card.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (40, 'human', '2024-07-22', '2024-06-30', 'Ativo', 'Curtis Brown', 'Sing during rock campaign decision. Public trial country those stock outside yeah. Music help deal.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (41, 'arrive', '2024-02-02', '2024-08-30', 'Inativo', 'Raven Case', 'Star find part in. Very decision than note.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (42, 'consumer', '2024-08-04', '2024-04-01', 'Conclu�do', 'Mr. Justin Stanley', 'Career entire get dark. Fact ten answer model.
Style no cut able stage.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (43, 'allow', '2024-11-04', '2024-05-23', 'Conclu�do', 'Kristine Dennis', 'Produce both adult several audience figure lay. Hotel baby factor.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (44, 'party', '2024-06-01', '2024-01-26', 'Conclu�do', 'Lori Brown', 'Growth share girl its. Part huge picture moment.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (45, 'stage', '2024-05-29', '2024-07-27', 'Inativo', 'Carol Turner', 'Require range ever business everything.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (46, 'already', '2024-06-15', '2024-09-19', 'Ativo', 'Brian Curtis', 'Science short soldier author wrong. Toward indicate analysis chair own against.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (47, 'under', '2024-04-06', '2024-11-05', 'Conclu�do', 'David Valenzuela', 'Unit be physical. Policy seat including coach. Inside they American ago note people cup Congress.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (48, 'here', '2024-08-26', '2024-09-09', 'Conclu�do', 'Kari Thomas', 'Structure although social thing kind goal without.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (49, 'light', '2024-08-29', '2024-02-08', 'Conclu�do', 'Tammy Craig', 'Rise cold partner manage. Go establish around other.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (50, 'wrong', '2024-03-10', '2024-11-16', 'Inativo', 'Kathleen Willis', 'Understand bring both rather I stand. Stop to ability right. Year specific station.');

-- Inser��es para a tabela dim_vaga
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (1, 'Editor, magazine features', 7, 'Feeling use garden break forget research night study watch yourself white.', 'Fechada', 'South Kevinmouth', 'Leslie Rivera');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (2, 'Airline pilot', 2, 'Beat well general can special or.', 'Aberta', 'Lake Elizabeth', 'Heather Contreras');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (3, 'Engineer, mining', 2, 'Light general really shoulder carry say price because have media Democrat trip popular.', 'Fechada', 'Melissaside', 'Ryan Hall');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (4, 'Conservator, furniture', 10, 'Agree night Democrat base accept her system.', 'Em andamento', 'West Jennifermouth', 'Danielle Williams');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (5, 'Editorial assistant', 7, 'Phone dinner hot way station best dog color board listen mind ago discuss.', 'Aberta', 'East Brianview', 'Scott Horton');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (6, 'Acupuncturist', 1, 'Miss grow fall total often business pull agree store think realize.', 'Aberta', 'Adamsville', 'Austin Walker');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (7, 'Community pharmacist', 4, 'Score consider dog customer number include two mind.', 'Aberta', 'North Reginafort', 'Thomas Molina');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (8, 'Physiotherapist', 2, 'Find whatever church who state court television amount sometimes last.', 'Em andamento', 'North Luisville', 'William Gallagher');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (9, 'Quantity surveyor', 9, 'Must senior partner today ball wait defense local material certain morning allow.', 'Em andamento', 'Port Lori', 'Nichole Davis');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (10, 'Environmental education officer', 1, 'Know great treatment unit through save land for establish attack power none rise make.', 'Aberta', 'Villarrealmouth', 'Kristin Peterson');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (11, 'Warehouse manager', 1, 'Effect actually near like spend stay others various need.', 'Em andamento', 'West Paul', 'James Mcdonald');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (12, 'Restaurant manager', 2, 'Whom agency range design before area according sister bed coach indicate three.', 'Aberta', 'Harryside', 'Tracey Kelly');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (13, 'Patent examiner', 4, 'Identify population before a stock consider receive common test.', 'Aberta', 'South Robertmouth', 'Michelle Baker');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (14, 'Nutritional therapist', 10, 'Market popular strong hot wind policy fly everyone son do serious when.', 'Aberta', 'Deannaside', 'Heather Diaz');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (15, 'Counselling psychologist', 9, 'Mrs official wind that among indicate think close fine off question current name.', 'Aberta', 'Danielland', 'Elizabeth Martinez');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (16, 'Office manager', 6, 'Six value rich student only capital image cultural within society.', 'Fechada', 'Timothyville', 'Richard Nelson');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (17, 'Psychologist, occupational', 8, 'During much heart against attention for feel act mission worry.', 'Em andamento', 'Lake Bruce', 'Diane Turner');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (18, 'Restaurant manager', 4, 'Wrong news dream join leader piece per again discuss.', 'Aberta', 'Lauraland', 'Abigail Roberts');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (19, 'Therapeutic radiographer', 5, 'Light seven area nearly part moment fill keep every left.', 'Fechada', 'Katherineport', 'Debbie Norton');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (20, 'Health service manager', 1, 'Present threat middle another city middle others suggest agent tend chance product.', 'Fechada', 'South Autumnchester', 'Andre Vargas');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (21, 'Legal secretary', 2, 'Other network site must natural current plan she compare class.', 'Aberta', 'Aprilmouth', 'Teresa Anderson');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (22, 'Counsellor', 8, 'Real upon meeting meet the among.', 'Fechada', 'New Donna', 'Ashley Munoz');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (23, 'Meteorologist', 1, 'Too where entire school south moment.', 'Fechada', 'Campbellmouth', 'Andrea Hanson');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (24, 'Naval architect', 9, 'American third if record agent service our whole person right member themselves up.', 'Aberta', 'Brownfurt', 'Melanie Schmidt');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (25, 'Horticulturist, amenity', 7, 'Catch threat among quickly opportunity born small thousand marriage.', 'Fechada', 'Wallaceberg', 'Kelsey Marshall');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (26, 'Psychotherapist, dance movement', 10, 'Increase long compare reason nearly share paper serious PM me involve.', 'Fechada', 'Port Davidport', 'Jamie Craig');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (27, 'Scientist, product/process development', 9, 'Effect responsibility maybe kitchen bag those seven page stock grow we.', 'Em andamento', 'Kellyside', 'Jonathan Larson');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (28, 'Armed forces operational officer', 2, 'Board visit animal gas class computer style artist phone.', 'Aberta', 'East Scottbury', 'Christopher Choi');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (29, 'Chemical engineer', 1, 'Knowledge artist operation natural value ask exist day.', 'Aberta', 'East Jodi', 'Henry Jones');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (30, 'Administrator, charities/voluntary organisations', 10, 'Remain story line table as way manage check include whom box address image.', 'Aberta', 'New Tommy', 'Brittany Bailey');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (31, 'Tourist information centre manager', 4, 'With number ball while head true green top its live reason number official base.', 'Fechada', 'Millershire', 'Evelyn Grant');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (32, 'Engineer, electronics', 7, 'Ever mean south life teach action skill middle second pretty project source.', 'Fechada', 'Jamiestad', 'Norman Reilly');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (33, 'Dealer', 1, 'First tend from bit fast without.', 'Fechada', 'Bellmouth', 'Tiffany Vaughan');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (34, 'Health physicist', 6, 'New consider fire job strategy image third apply rest these church town.', 'Aberta', 'North Lucasborough', 'Angela Quinn');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (35, 'Sports coach', 6, 'Congress exist range actually old argue central important.', 'Fechada', 'North Alexa', 'Dakota Bryant');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (36, 'Exercise physiologist', 6, 'Threat ability teacher father sit hour husband here traditional skin theory compare forget.', 'Em andamento', 'Penningtonfort', 'Isaiah Gaines');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (37, 'Programmer, applications', 5, 'Play stock hair other almost single charge.', 'Aberta', 'Jamesport', 'Daniel Wright');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (38, 'Corporate treasurer', 8, 'Play level best third test bank citizen herself computer.', 'Em andamento', 'Randallshire', 'Jeffrey Bowers');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (39, 'Nature conservation officer', 7, 'Pm heavy sister road bring relate hot lead.', 'Aberta', 'Royshire', 'Timothy Mack');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (40, 'Scientist, audiological', 5, 'Late nearly put describe assume crime risk fly economy matter how.', 'Em andamento', 'South Jermainetown', 'Destiny Lopez');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (41, 'Scientist, audiological', 7, 'Congress question TV half economy let term environment performance light expert.', 'Fechada', 'Veronicaside', 'Keith Summers');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (42, 'Lecturer, further education', 6, 'Pass create rather memory be fire analysis development charge skill.', 'Aberta', 'North Michaelland', 'Elizabeth Figueroa MD');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (43, 'Occupational hygienist', 1, 'Low run be seat scientist author feeling enjoy.', 'Em andamento', 'Lake Kellyside', 'Stacey Lyons');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (44, 'Public house manager', 7, 'Vote according more bad central education stand young arrive.', 'Em andamento', 'New Chris', 'John Randall');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (45, 'Therapist, nutritional', 6, 'Affect lot pass big yard company future drug room.', 'Aberta', 'East Eric', 'Samuel Stone');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (46, 'Chiropractor', 7, 'Under PM surface else perhaps life left already blood work use.', 'Fechada', 'East Tonyaton', 'Kristin Lowe DVM');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (47, 'Communications engineer', 9, 'Room word near discuss whom important create.', 'Aberta', 'Nataliefurt', 'Matthew Rollins');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (48, 'Brewing technologist', 4, 'House ten gun article central country inside away director blue.', 'Aberta', 'New Davidview', 'John Martinez');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (49, 'Armed forces training and education officer', 4, 'Us capital image discover organization call.', 'Fechada', 'Scotthaven', 'Jimmy Banks');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (50, 'Medical technical officer', 1, 'Peace notice force girl customer senior.', 'Fechada', 'Marshallmouth', 'Joseph Keller');

