-- Inserções para a tabela users
INSERT INTO users (login, password, role, grupo_id) VALUES ('dianalee', 'vWQ!6Hpsvv', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('stevensoncristian', '@PTMag3ak7', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('russell89', '#g1vWjVnsc', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('cmejia', '9^%9MWsphR', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('arianagarcia', '&W!1CHjd!M', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('danielsjacob', 'kPE1C^ty@j', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('markwilliams', 'Q+TYGGmy@7', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('aaron57', 'E&7I3kNg7h', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('conleyterry', 'G(QA1ZAopo', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('joannabailey', '^41lbUnbx0', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('caldwelldaniel', '&B1XqzdD^j', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('snyderbrittany', '8_5oNYcA+0', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('dchandler', 'c*g5IdNn8(', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('williamsstacey', 'mEt9Xsy(W@', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('patrick08', '19_6DvQx$@', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('wilsonsummer', '!cNvHJ_hy6', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('qschultz', '#4)NZve4#w', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('william56', 'VXTGKOl+*1', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('darrenlee', 'vyCLPzdt$8', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('zacharytaylor', '%uS0FmbcYP', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('zblake', 'edeOG(LI*1', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('shelly98', 'PKu5OF0e!%', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('rgallagher', '@00ck*Tl(y', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('cdean', 't*IS9Y9o$G', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('brandonhernandez', 'ob57qEq@^n', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('tonya62', '%7q6AVgkz4', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ujames', 'T5CG8Gol_y', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('nanderson', 'i6nXWn+4*H', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('randall08', '$_1GEcFsfI', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('greenbeverly', '1ro5Ejfz$m', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('wjohnson', 'T*W462PcVR', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('onicholson', 's0!4VGIaSi', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('gellison', 'vcPV^ToO(6', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('denise14', 'T+)PUSn()4', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('murraykathy', ')i4zEKVgHw', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('john18', '_Hf6Jh%x3!', 'Manager', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('ahopkins', 's_tI85!lbJ', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('torrescarol', '(Hh3KajbW$', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('william77', '(TEM87CeGH', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('nguyenhenry', '(8TWfs3Q_0', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('henrychristine', '_fYVW1co47', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('gary14', '%vgdDwXC62', 'Manager', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('gphelps', '_lc7lIRm2O', 'Admin', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('dfloyd', 'sgoNxxH6%3', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('hwallace', 'I8L78Ox6#w', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('russell31', '%ta84Nn4L6', 'User', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('robertwalker', '5I0(O%jw^(', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('patelmelissa', ')60r8GwZ&H', 'User', 1);
INSERT INTO users (login, password, role, grupo_id) VALUES ('christopherjohnson', '_v*8PC^qj8', 'Admin', 2);
INSERT INTO users (login, password, role, grupo_id) VALUES ('jason69', 'e@f9I0useI', 'Admin', 2);

-- Inserções para a tabela config_Indicador
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('create', 'score', '<', '82', 'concern', 'north', '>=', '9', 'brodriguez', 'Education personal for discover like make customer bill.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('various', 'record', '<', '43', 'do', 'young', '<', '89', 'cynthiablevins', 'My civil woman inside talk door oil mean medical.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('knowledge', 'social', '>', '18', 'surface', 'because', '>', '81', 'turnerjesse', 'Down design themselves make better challenge training religious receive include strategy common else.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('evening', 'church', '<', '92', 'relate', 'interesting', '=', '44', 'victoriakelly', 'Street write challenge toward fall discover.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('girl', 'action', '=', '80', 'rest', 'lawyer', '>', '28', 'jonathonburton', 'Make television interesting sense indicate true wide law east someone choose.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('song', 'prepare', '>', '78', 'few', 'take', '>', '54', 'psexton', 'Call office move wife she behavior individual parent watch theory sell house hold.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('front', 'kid', '=', '2', 'prove', 'vote', '<', '15', 'zwilliams', 'Worry far three present game result issue.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('standard', 'site', '<=', '1', 'see', 'or', '>=', '41', 'asimmons', 'Respond maintain must me game school have local dream school debate.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('field', 'kind', '>=', '65', 'exactly', 'write', '=', '70', 'dave05', 'Keep watch show project rather majority few would.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('knowledge', 'fund', '=', '48', 'body', 'candidate', '<', '21', 'gregorycolleen', 'State bed suddenly when else debate poor suggest.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('part', 'consider', '>=', '51', 'according', 'writer', '=', '100', 'samuel76', 'Artist price amount short stop level study sit.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('enough', 'ability', '<=', '66', 'paper', 'according', '<=', '16', 'megan03', 'Serve image mind happy inside make camera.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('responsibility', 'morning', '<=', '96', 'key', 'change', '>=', '82', 'rachelyoung', 'Foreign side data name pick sense five third throw risk long mean trip.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('mind', 'head', '>', '68', 'protect', 'fish', '>=', '6', 'angel32', 'Change challenge soldier up test surface or air someone.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('key', 'group', '<', '97', 'economic', 'share', '=', '56', 'kenneth90', 'Share sure performance it world hospital campaign Republican political.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('social', 'environment', '>', '97', 'fight', 'trouble', '>', '16', 'mccallbriana', 'Road how candidate each unit but statement beat any.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('six', 'whose', '=', '76', 'police', 'something', '<=', '81', 'paul40', 'Artist number dinner around suggest speak beautiful item organization without security fly.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('course', 'if', '>', '36', 'kid', 'example', '<', '79', 'brianwalter', 'Its hotel listen answer majority score center majority they no forget.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('push', 'product', '>', '59', 'prove', 'pattern', '=', '46', 'vkelly', 'Give visit art figure federal most goal development size first.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('join', 'figure', '=', '41', 'poor', 'later', '=', '88', 'nancywilliams', 'Few mouth game dog cause politics rise describe keep break customer theory reduce.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('even', 'report', '<=', '47', 'true', 'out', '>', '96', 'lcarroll', 'Serve letter range hold garden which lot.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('store', 'difference', '>', '31', 'seat', 'week', '>=', '78', 'tmyers', 'Up democratic suggest use five tonight apply couple tend often situation alone.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('able', 'window', '>=', '32', 'player', 'trouble', '>', '94', 'freemanmelissa', 'Matter hour owner building data magazine build possible room question.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('approach', 'though', '<', '34', 'fish', 'tend', '>=', '38', 'melissastevens', 'Sea almost PM major resource the again interesting hair central.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('others', 'anything', '<=', '75', 'skill', 'until', '<=', '60', 'rrollins', 'They five election try nor sound trouble gun.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('several', 'coach', '>=', '34', 'research', 'foot', '>', '57', 'tmorales', 'Win imagine ahead blood hundred week improve operation do sure laugh course.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('already', 'however', '=', '51', 'cell', 'laugh', '=', '36', 'delgadotravis', 'Listen pay draw similar in adult.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('himself', 'apply', '>=', '13', 'study', 'home', '<=', '9', 'beckercheryl', 'Walk become ready upon wind thus all others close exactly.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('list', 'part', '<', '3', 'alone', 'event', '>=', '28', 'diazmary', 'Memory kid land cell above push individual coach attention fact.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('never', 'operation', '=', '58', 'difficult', 'central', '>', '69', 'traceyhudson', 'Hand painting occur moment south section part.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('event', 'give', '<', '11', 'buy', 'likely', '>', '98', 'matthew39', 'Race political indicate practice movement order loss general upon attack general show since.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('bad', 'trade', '=', '30', 'prepare', 'level', '=', '50', 'gbaker', 'Four future do summer life region expect tend above in read would.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('draw', 'cost', '>', '26', 'understand', 'science', '<', '23', 'ybennett', 'Attention medical around main writer area throughout able consider stand time.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('rather', 'college', '<=', '17', 'trade', 'opportunity', '>=', '23', 'seanjohnson', 'Election win positive model across political.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('we', 'anyone', '<', '12', 'fire', 'rich', '<=', '33', 'wilsonshawn', 'Body security case instead claim let different.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('cell', 'history', '<=', '50', 'present', 'set', '<=', '45', 'gatesmichael', 'Yet room research issue move interview test.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('need', 'other', '=', '91', 'make', 'window', '>=', '4', 'xscott', 'Dog money move tell candidate beyond discuss travel.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('movement', 'guess', '>=', '28', 'professor', 'seem', '<', '80', 'mmitchell', 'Box opportunity thus offer sea air alone lot significant show.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('a', 'camera', '>=', '43', 'bank', 'society', '<', '31', 'bradley40', 'Discussion near something majority middle public within himself meet wind.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('character', 'pretty', '<=', '80', 'outside', 'simple', '=', '77', 'jwalton', 'Walk someone kind game face race fill grow chair carry answer culture.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('community', 'three', '<=', '50', 'fire', 'soon', '<=', '82', 'kingstephanie', 'Knowledge teacher media summer quite discussion.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('together', 'boy', '<=', '55', 'boy', 'weight', '>', '26', 'linscott', 'So travel training whole away chair really task manage.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('government', 'fine', '>=', '80', 'a', 'listen', '>=', '51', 'amandabell', 'Carry statement drug morning nearly force personal.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('environment', 'method', '=', '95', 'explain', 'high', '<', '63', 'philip89', 'More high figure statement Republican nice discover.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('Mr', 'prepare', '>=', '30', 'carry', 'newspaper', '>=', '31', 'jennifer07', 'May one day take nor he finish will under sometimes.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('activity', 'carry', '<=', '48', 'happen', 'billion', '<=', '48', 'jramos', 'Cut include create do finish method whether single.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('yet', 'decade', '>=', '69', 'continue', 'land', '>=', '25', 'timothylittle', 'Determine movie reason tree use though health front affect will make.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('key', 'matter', '<=', '84', 'memory', 'enjoy', '>=', '36', 'jacobslisa', 'Leave than full more cause painting both late five.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('lawyer', 'city', '>', '67', 'little', 'kid', '=', '99', 'halldylan', 'Happen through western growth major run face serve.');
INSERT INTO config_Indicador (indicador_nome, indicador_campo, indicador_comparador, indicador_valor, filtro_nome, filtro_campo, filtro_comparador, filtro_valor, usuario, descricao) VALUES ('rate', 'national', '<=', '36', 'tend', 'along', '=', '23', 'wrightmichael', 'Side save stop fly class early lose cut last reveal.');

-- Inserções para a tabela dim_acao_seletiva
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (1, 'Tipo B', '2024-11-03');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (2, 'Tipo B', '2024-11-16');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (3, 'Tipo B', '2024-11-23');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (4, 'Tipo C', '2024-01-29');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (5, 'Tipo A', '2024-01-18');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (6, 'Tipo C', '2024-03-20');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (7, 'Tipo C', '2024-08-29');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (8, 'Tipo B', '2024-06-19');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (9, 'Tipo B', '2024-03-18');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (10, 'Tipo B', '2024-08-08');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (11, 'Tipo C', '2024-02-22');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (12, 'Tipo A', '2024-09-28');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (13, 'Tipo A', '2024-02-02');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (14, 'Tipo A', '2024-05-04');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (15, 'Tipo C', '2024-09-20');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (16, 'Tipo B', '2024-03-27');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (17, 'Tipo A', '2024-10-20');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (18, 'Tipo B', '2024-05-12');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (19, 'Tipo B', '2024-03-05');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (20, 'Tipo C', '2024-05-24');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (21, 'Tipo B', '2024-06-05');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (22, 'Tipo A', '2024-09-06');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (23, 'Tipo B', '2024-07-31');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (24, 'Tipo A', '2024-03-18');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (25, 'Tipo A', '2024-01-19');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (26, 'Tipo C', '2024-03-03');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (27, 'Tipo A', '2024-05-06');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (28, 'Tipo A', '2024-07-31');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (29, 'Tipo C', '2024-11-02');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (30, 'Tipo C', '2024-07-06');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (31, 'Tipo A', '2024-07-27');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (32, 'Tipo B', '2024-06-17');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (33, 'Tipo A', '2024-09-01');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (34, 'Tipo A', '2024-07-08');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (35, 'Tipo A', '2024-06-24');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (36, 'Tipo C', '2024-09-11');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (37, 'Tipo A', '2024-06-03');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (38, 'Tipo C', '2024-10-27');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (39, 'Tipo A', '2024-09-11');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (40, 'Tipo A', '2024-03-13');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (41, 'Tipo A', '2024-10-16');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (42, 'Tipo B', '2024-09-15');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (43, 'Tipo C', '2024-03-10');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (44, 'Tipo C', '2024-02-03');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (45, 'Tipo A', '2024-04-24');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (46, 'Tipo A', '2024-11-09');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (47, 'Tipo C', '2024-03-24');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (48, 'Tipo A', '2024-11-22');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (49, 'Tipo C', '2024-08-28');
INSERT INTO dim_acao_seletiva (id_dim_acao_seletiva, tipo, dt_hora) VALUES (50, 'Tipo B', '2024-04-07');

-- Inserções para a tabela dim_contratacao
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (1, '2024-05-14', 13837.02, 2, '2024-03-31');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (2, '2024-09-09', 11594.03, 3, '2024-07-05');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (3, '2024-09-29', 4073.59, 2, '2024-03-05');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (4, '2024-08-10', 7370.32, 1, '2024-10-31');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (5, '2024-02-02', 4761.93, 3, '2024-02-22');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (6, '2024-04-25', 5801.35, 1, '2024-07-02');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (7, '2024-02-15', 5998.38, 1, '2024-03-11');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (8, '2024-06-30', 5670.89, 1, '2024-04-17');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (9, '2024-03-15', 14647.0, 2, '2024-11-10');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (10, '2024-08-23', 13228.52, 3, '2024-06-07');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (11, '2024-07-12', 3163.92, 2, '2024-11-03');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (12, '2024-07-01', 13669.02, 1, '2024-06-05');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (13, '2024-02-02', 11577.9, 3, '2024-06-24');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (14, '2024-02-20', 8120.31, 3, '2024-03-29');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (15, '2024-07-19', 11902.0, 3, '2024-10-12');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (16, '2024-10-19', 9073.35, 3, '2024-05-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (17, '2024-08-16', 8023.53, 1, '2024-05-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (18, '2024-02-18', 7785.29, 2, '2024-03-31');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (19, '2024-06-17', 11887.12, 1, '2024-06-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (20, '2024-10-12', 12562.69, 3, '2024-05-10');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (21, '2024-10-25', 7934.46, 3, '2024-05-21');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (22, '2024-11-07', 9548.97, 3, '2024-09-10');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (23, '2024-09-23', 10219.54, 2, '2024-08-04');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (24, '2024-01-26', 5767.98, 3, '2024-03-11');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (25, '2024-11-16', 9022.44, 3, '2024-11-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (26, '2024-04-09', 6996.49, 1, '2024-02-09');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (27, '2024-07-23', 13721.13, 3, '2024-07-06');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (28, '2024-06-17', 7846.45, 2, '2024-02-19');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (29, '2024-07-05', 9247.68, 2, '2024-04-30');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (30, '2024-07-15', 6399.95, 3, '2024-07-02');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (31, '2024-06-02', 4689.85, 2, '2024-03-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (32, '2024-03-18', 7523.13, 2, '2024-02-11');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (33, '2024-04-25', 7542.62, 2, '2024-02-22');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (34, '2024-06-03', 10046.74, 1, '2024-11-16');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (35, '2024-01-08', 9499.87, 1, '2024-03-15');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (36, '2024-04-12', 3411.98, 2, '2024-03-01');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (37, '2024-08-11', 8811.94, 1, '2024-08-13');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (38, '2024-03-16', 10247.25, 2, '2024-09-05');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (39, '2024-06-09', 5621.23, 2, '2024-03-20');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (40, '2024-04-26', 9353.2, 2, '2024-01-31');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (41, '2024-02-23', 6840.37, 3, '2024-09-17');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (42, '2024-04-14', 13084.74, 3, '2024-03-07');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (43, '2024-08-13', 13117.68, 2, '2024-09-09');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (44, '2024-05-13', 11744.51, 1, '2024-01-31');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (45, '2024-06-16', 9783.55, 3, '2024-02-10');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (46, '2024-03-21', 6185.39, 1, '2024-03-18');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (47, '2024-05-25', 14182.88, 1, '2024-11-07');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (48, '2024-01-30', 9165.77, 2, '2024-07-23');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (49, '2024-08-16', 12027.25, 1, '2024-07-21');
INSERT INTO dim_contratacao (id_dim_contratacao, dt_contratacao, salario_inicial, tipo_contrato, dt_aceite_oferta) VALUES (50, '2024-06-24', 3676.11, 1, '2024-01-21');

-- Inserções para a tabela dim_entrevista
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (1, '2024-08-02', 'Nathan Anderson II', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (2, '2024-05-01', 'Donald Fernandez', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (3, '2024-04-16', 'Jack Davis', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (4, '2024-02-05', 'Paul Davis Jr.', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (5, '2024-11-08', 'Daniel Rios', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (6, '2024-07-01', 'Michael Smith', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (7, '2024-11-23', 'Thomas Fisher', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (8, '2024-01-07', 'Samuel Gibson', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (9, '2024-08-05', 'Kara Vincent', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (10, '2024-03-28', 'Robert Carpenter', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (11, '2024-04-02', 'Christopher Nelson', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (12, '2024-08-09', 'Sergio Smith', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (13, '2024-06-22', 'Robert Sanders', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (14, '2024-10-08', 'Wanda Hill', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (15, '2024-01-26', 'Mr. Thomas Harris', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (16, '2024-01-15', 'Ricky Payne', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (17, '2024-02-01', 'Zachary Baxter', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (18, '2024-04-22', 'Tamara Sanchez', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (19, '2024-07-26', 'Christopher Cole', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (20, '2024-06-05', 'Kevin Mccoy', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (21, '2024-02-19', 'Summer Paul', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (22, '2024-11-27', 'Patricia Willis', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (23, '2024-08-13', 'Paige Nicholson', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (24, '2024-11-18', 'Hector Wilson', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (25, '2024-10-31', 'Robert Daugherty', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (26, '2024-10-14', 'Justin Myers', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (27, '2024-05-02', 'Erin Tate', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (28, '2024-10-05', 'Eric Davis', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (29, '2024-05-02', 'Brooke Le', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (30, '2024-09-25', 'Stephanie Williamson', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (31, '2024-03-04', 'Kylie Mullins', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (32, '2024-05-27', 'Tyler Burke', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (33, '2024-11-24', 'Rebecca Miller', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (34, '2024-07-17', 'Kimberly Young', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (35, '2024-09-29', 'Amanda Lee', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (36, '2024-03-22', 'Courtney Hill', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (37, '2024-07-23', 'Zachary Phillips', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (38, '2024-02-12', 'Samantha Elliott', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (39, '2024-02-22', 'Amanda Brown', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (40, '2024-05-22', 'Jake Wright', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (41, '2024-05-02', 'Mark Rodgers', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (42, '2024-08-02', 'Michael Clark', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (43, '2024-05-18', 'Michael Contreras', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (44, '2024-02-22', 'Krystal Harper', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (45, '2024-07-17', 'Kevin Barber', 'Aprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (46, '2024-08-12', 'Timothy Martin', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (47, '2024-05-23', 'Carl Gallagher', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (48, '2024-07-10', 'Kathleen Adams', 'Reprovado');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (49, '2024-07-30', 'Paul Braun', 'Em análise');
INSERT INTO dim_entrevista (id_dim_entrevista, dt_entrevista, entrevistador, resultado) VALUES (50, '2024-07-11', 'William Kelley', 'Aprovado');

-- Inserções para a tabela dim_feedback
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (1, 'Different husband against specific city drug huge want.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (2, 'Republican notice campaign alone many direction model behind.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (3, 'Focus pattern admit our standard wait ready site listen worker work contain point.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (4, 'Box month would popular adult service call account figure here.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (5, 'Scene with perform beat stay gas bring describe author class base.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (6, 'Effort appear food month according believe edge cold box culture student.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (7, 'Past weight month employee fill member politics sometimes direction.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (8, 'Positive training question share in everybody tree why.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (9, 'Weight even throughout side best become than court pattern civil one knowledge.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (10, 'Somebody keep concern democratic teacher prepare others hot stock game.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (11, 'Push everyone into put kind size animal fly man different.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (12, 'Start series air full about body rate often truth west cell.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (13, 'Pressure million though others member anything establish.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (14, 'Agreement imagine discussion measure business someone.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (15, 'Choose people movie ever music Democrat performance statement relate about back rich quite.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (16, 'Learn or guy happy technology others science information.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (17, 'Near example begin boy hard drug protect quickly little back food whatever even.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (18, 'Lay book remain great box amount product report class public course feel fact.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (19, 'Decision technology ten choice product hospital.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (20, 'Buy cause important receive source adult nature energy safe.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (21, 'Reach report since watch local performance its international conference true.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (22, 'Thousand already same life pick article investment open capital manage painting last.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (23, 'Too site baby Mrs protect care something discuss draw national.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (24, 'Thing major any only number single whom month rise.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (25, 'Worry and exist recognize actually together trade level.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (26, 'Environmental test capital within art issue miss American.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (27, 'Measure statement though mean note training.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (28, 'Off certain you blood or value response receive light tax wall door training.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (29, 'Hour spend level protect win how city leg news water street forward weight.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (30, 'Shake true foreign data yeah whole baby fund.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (31, 'Health say tend coach out type production anything contain change sign rather bank particularly.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (32, 'Month moment bar compare believe personal.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (33, 'Heart professional boy arm theory continue TV approach wind modern we.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (34, 'Citizen mention our American control kid.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (35, 'Two fight significant save range artist pretty environment enter notice past worry.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (36, 'Much can institution collection garden final heart activity institution ground today theory.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (37, 'Campaign wind sure yes modern line.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (38, 'Cut yourself shoulder wear compare paper evidence issue bill reality.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (39, 'Education somebody political beyond ahead threat important speech establish maybe.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (40, 'Reduce watch middle nothing set religious themselves fast born investment reality foreign draw.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (41, 'Within board model right likely possible movement.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (42, 'Staff wide home every accept education young.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (43, 'Will step strategy option call tree short you contain may form.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (44, 'Member soon standard new hear still relate choose in trial fall.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (45, 'Law approach reason reality imagine card run early decision and chance later read.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (46, 'Ability quite notice then cell serious.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (47, 'Way stand discuss themselves actually either across skin forward new control.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (48, 'Actually whatever radio should final ready.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (49, 'System movement cover off fight sign network arm threat.');
INSERT INTO dim_feedback (id_dim_feedback, descricao) VALUES (50, 'President build trip century much put on might same physical many.');

-- Inserções para a tabela dim_participante_rh
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (1, 'Timothy Brown', 'Teacher, special educational needs');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (2, 'Jennifer Simmons', 'Trade union research officer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (3, 'Karen Taylor', 'Solicitor');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (4, 'Tara Goodman', 'Museum education officer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (5, 'Elizabeth Evans', 'Runner, broadcasting/film/video');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (6, 'Joseph Miranda', 'Producer, radio');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (7, 'Brendan Wilson', 'Surveyor, minerals');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (8, 'Robert Vega', 'Senior tax professional/tax inspector');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (9, 'Jennifer Wood', 'Biomedical engineer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (10, 'Bobby Jackson', 'Occupational psychologist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (11, 'Jennifer Bentley', 'Technical brewer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (12, 'Nicholas Simmons', 'Telecommunications researcher');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (13, 'Eric Smith', 'Editor, magazine features');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (14, 'Leonard Hart', 'Equities trader');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (15, 'Gabriel Fields', 'Pharmacist, community');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (16, 'Clifford Hernandez', 'Copy');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (17, 'Kathy Harris', 'Education officer, community');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (18, 'Mark Morris', 'Podiatrist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (19, 'Jeremy Murray', 'Speech and language therapist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (20, 'Anthony Saunders', 'Herpetologist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (21, 'Linda Hendricks', 'Advice worker');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (22, 'Karen Shepard', 'Chiropractor');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (23, 'Mikayla Allison', 'Special effects artist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (24, 'Deanna Walker', 'Broadcast engineer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (25, 'Tommy Johnson', 'Television production assistant');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (26, 'Adam Meyer', 'Engineer, electronics');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (27, 'Kyle Powers', 'Computer games developer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (28, 'Michael Ramsey PhD', 'Chiropractor');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (29, 'Mark Howard', 'Agricultural consultant');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (30, 'Christopher Henderson', 'Conservation officer, historic buildings');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (31, 'Peter White', 'Engineer, automotive');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (32, 'Joseph Smith', 'Musician');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (33, 'Elizabeth Carson', 'Agricultural consultant');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (34, 'Rachel Riley', 'Research officer, political party');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (35, 'Mr. Nathaniel Roberts', 'Patent attorney');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (36, 'Cody Fischer', 'Furniture designer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (37, 'Dennis Schmidt', 'Logistics and distribution manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (38, 'Amanda Mason', 'Licensed conveyancer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (39, 'Alison Flores', 'Engineer, agricultural');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (40, 'Steven Whitaker', 'Designer, ceramics/pottery');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (41, 'David Garcia', 'Pathologist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (42, 'Patrick Wilson', 'Biomedical engineer');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (43, 'Brian Peck', 'Medical physicist');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (44, 'Jacob Stone', 'Print production planner');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (45, 'Mark Welch', 'Tourist information centre manager');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (46, 'Laura Ramirez', 'Copywriter, advertising');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (47, 'Tabitha Hill', 'Teacher, English as a foreign language');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (48, 'Carol Robbins', 'Therapist, horticultural');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (49, 'Evan Hanson', 'Public librarian');
INSERT INTO dim_participante_rh (id_dim_participante_rh, nome, cargo) VALUES (50, 'Jason Wilcox', 'Restaurant manager');

-- Inserções para a tabela dim_periodo
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (1, '2024-01-14', '2024-09-24');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (2, '2024-10-11', '2024-11-04');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (3, '2024-01-08', '2024-01-09');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (4, '2024-11-17', '2024-07-17');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (5, '2024-01-12', '2024-08-15');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (6, '2024-04-27', '2024-04-27');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (7, '2024-06-20', '2024-11-16');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (8, '2024-05-30', '2024-06-28');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (9, '2024-09-12', '2024-07-12');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (10, '2024-09-10', '2024-06-13');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (11, '2024-08-02', '2024-05-11');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (12, '2024-10-16', '2024-07-27');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (13, '2024-10-19', '2024-09-26');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (14, '2024-07-24', '2024-04-24');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (15, '2024-05-16', '2024-02-13');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (16, '2024-05-17', '2024-02-02');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (17, '2024-08-12', '2024-09-02');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (18, '2024-10-14', '2024-09-15');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (19, '2024-04-08', '2024-09-28');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (20, '2024-01-25', '2024-08-27');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (21, '2024-02-11', '2024-09-10');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (22, '2024-05-31', '2024-09-18');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (23, '2024-11-25', '2024-11-28');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (24, '2024-04-30', '2024-09-21');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (25, '2024-02-07', '2024-08-06');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (26, '2024-08-28', '2024-07-14');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (27, '2024-11-01', '2024-01-28');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (28, '2024-02-01', '2024-06-17');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (29, '2024-02-06', '2024-09-18');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (30, '2024-03-21', '2024-09-10');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (31, '2024-05-22', '2024-08-20');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (32, '2024-04-12', '2024-08-11');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (33, '2024-06-23', '2024-08-25');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (34, '2024-01-28', '2024-12-11');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (35, '2024-01-28', '2024-02-22');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (36, '2024-05-26', '2024-07-05');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (37, '2024-05-17', '2024-10-01');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (38, '2024-09-25', '2024-07-11');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (39, '2024-04-08', '2024-04-24');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (40, '2024-05-03', '2024-08-27');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (41, '2024-01-15', '2024-05-20');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (42, '2024-04-19', '2024-02-06');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (43, '2024-08-16', '2024-02-22');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (44, '2024-06-01', '2024-12-06');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (45, '2024-11-22', '2024-03-04');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (46, '2024-10-04', '2024-03-09');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (47, '2024-02-11', '2024-07-11');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (48, '2024-10-26', '2024-06-13');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (49, '2024-06-18', '2024-12-01');
INSERT INTO dim_periodo (id_dim_periodo, dt_abertura, dt_fechamento) VALUES (50, '2024-02-23', '2024-07-30');

-- Inserções para a tabela dim_processo_seletivo
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (1, 'letter', '2024-03-11', '2024-05-17', 'Inativo', 'Ashley Olson', 'Pull huge son blue as. Best yard play society.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (2, 'race', '2024-04-12', '2024-11-06', 'Concluído', 'Alyssa Wilson', 'West tree that official. Nearly student wish her sell.
Leave movement example.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (3, 'conference', '2024-09-07', '2024-06-22', 'Inativo', 'Jim Coleman', 'Strategy huge team those. Be seek official watch easy environment once.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (4, 'name', '2024-03-23', '2024-06-13', 'Ativo', 'Nicholas Dawson', 'Outside into both they. Sense will order and manager. Keep civil reach.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (5, 'team', '2024-02-06', '2024-06-12', 'Inativo', 'Mr. Jacob Ryan', 'Treatment writer structure answer fear memory worker. According later run interest.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (6, 'they', '2024-06-02', '2024-02-13', 'Ativo', 'Gabriel Gonzales', 'Even establish give whose day.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (7, 'own', '2024-11-25', '2024-07-20', 'Ativo', 'Grace Diaz', 'Able leg everyone when market fall gas. Policy last fund purpose computer lay.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (8, 'because', '2024-07-12', '2024-10-29', 'Inativo', 'Erin Martin', 'After wife product as everybody ago.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (9, 'process', '2024-07-13', '2024-09-30', 'Ativo', 'Emma Wright', 'Activity theory spring no they start.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (10, 'lose', '2024-10-04', '2024-05-24', 'Ativo', 'Paul Harris', 'Ago information military might. Live suffer front individual.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (11, 'test', '2024-11-01', '2024-07-25', 'Concluído', 'Nathan Ryan PhD', 'Agency skin modern form eat. Sure deal buy movement true way. Side though amount provide.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (12, 'worker', '2024-02-09', '2024-11-15', 'Ativo', 'Roy Warner', 'Face career well. Learn herself want region amount out nation.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (13, 'throw', '2024-04-20', '2024-06-13', 'Inativo', 'Robert Kelly', 'Future may major list share.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (14, 'war', '2024-01-23', '2024-02-12', 'Concluído', 'Cheryl Roberts', 'Century item by radio. Choice event once threat too. Yes option will test natural Democrat.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (15, 'TV', '2024-08-22', '2024-05-01', 'Concluído', 'Kimberly Fernandez', 'More board continue pressure movement spring drug. Radio door culture wait. Growth wrong stock.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (16, 'though', '2024-07-30', '2024-11-06', 'Concluído', 'Amanda Ponce', 'Fact there significant build begin. Hospital similar in forward cold decision light.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (17, 'when', '2024-09-20', '2024-11-19', 'Ativo', 'Cindy Parker', 'Treat this market. Here four item kitchen.
Firm professor south.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (18, 'court', '2024-04-18', '2024-08-29', 'Concluído', 'Mark Rios', 'Determine value wife truth require brother on large. Those interest thing eye dark stock.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (19, 'where', '2024-03-30', '2024-04-20', 'Ativo', 'Suzanne Hill', 'Beat letter owner fund throughout region job.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (20, 'interest', '2024-06-06', '2024-04-19', 'Inativo', 'Tim Alexander', 'Government cup various report serve. Second purpose party chair ready.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (21, 'should', '2024-01-26', '2024-08-08', 'Inativo', 'Micheal Vega', 'May discuss rule toward same book. Anyone old leg paper respond.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (22, 'their', '2024-02-25', '2024-03-09', 'Inativo', 'Mary Farmer', 'Common front lawyer. Trip off full. Cell point prove. Must owner team hair recently.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (23, 'sport', '2024-02-13', '2024-02-29', 'Ativo', 'Timothy Merritt', 'Spend your important information worker.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (24, 'pass', '2024-05-26', '2024-10-24', 'Ativo', 'Melinda Skinner', 'Night race child price. Resource teach himself customer black.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (25, 'give', '2024-07-09', '2024-10-01', 'Inativo', 'Michele Hatfield', 'Movement pattern threat rather. Baby decade particular no hand the.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (26, 'explain', '2024-08-17', '2024-11-20', 'Concluído', 'Teresa Hale', 'Perform town door. Capital school lead. Society practice sometimes on relationship nearly.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (27, 'maybe', '2024-03-08', '2024-07-18', 'Ativo', 'Julie Smith', 'Moment line future put draw. Mention each culture onto phone animal small.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (28, 'room', '2024-01-23', '2024-06-12', 'Concluído', 'Charles Becker', 'Wind stay mind daughter hit now follow. Civil land explain learn. Court attack white something.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (29, 'south', '2024-07-06', '2024-06-03', 'Concluído', 'Rachel Williams', 'Large arm fund past. Yourself fill admit second board down.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (30, 'stand', '2024-03-01', '2024-07-19', 'Ativo', 'Sarah Cooper', 'Action experience share inside service.
Agency senior analysis her.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (31, 'every', '2024-07-11', '2024-01-24', 'Inativo', 'William Cruz', 'Special unit top challenge. To might already rule.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (32, 'figure', '2024-08-07', '2024-12-06', 'Inativo', 'Ashley Andrews', 'Last popular remain choose pick pick. Local occur success particular.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (33, 'pay', '2024-04-15', '2024-03-06', 'Ativo', 'Jacqueline Brooks', 'Sea director itself general debate. Young fast activity college.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (34, 'ago', '2024-05-08', '2024-03-05', 'Inativo', 'John Steele', 'Major involve of system window. Action cause compare young. Air employee measure forget.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (35, 'matter', '2024-11-26', '2024-08-14', 'Concluído', 'Dr. Grace Mitchell', 'Pm control discussion ever. Say can region culture environmental her them right.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (36, 'just', '2024-01-18', '2024-04-24', 'Ativo', 'Thomas Weber', 'Democrat seven read yard book leader onto. Author show exist perform when.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (37, 'nice', '2024-03-08', '2024-03-27', 'Concluído', 'Jocelyn Barnes', 'Several federal standard cultural senior. Quickly process want production. Team doctor notice.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (38, 'history', '2024-05-13', '2024-02-24', 'Ativo', 'Brian Brown', 'Agent final world foreign newspaper. Young rule amount beautiful discover.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (39, 'explain', '2024-11-24', '2024-04-15', 'Concluído', 'Christopher Le', 'Cost stay shoulder business idea manage really.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (40, 'especially', '2024-05-10', '2024-10-07', 'Inativo', 'Nicholas Walls', 'Effort deal right oil here. Person step bar.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (41, 'give', '2024-04-28', '2024-03-01', 'Inativo', 'Damon Jones', 'Strategy different direction edge tree soon. Worker hotel probably very with senior look.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (42, 'real', '2024-03-14', '2024-11-24', 'Ativo', 'Christie Perez', 'Option by challenge imagine benefit style. Step trouble compare picture buy.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (43, 'itself', '2024-03-05', '2024-03-25', 'Inativo', 'Brian Johnson', 'Conference either identify money human. Sit station free team. Drive until industry street dark.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (44, 'do', '2024-03-07', '2024-05-30', 'Inativo', 'April Rios', 'Yes behavior she. Clear before adult safe.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (45, 'beautiful', '2024-08-16', '2024-03-01', 'Ativo', 'Darrell Valencia', 'They well stop parent inside. Under study white nature rule someone study.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (46, 'family', '2024-04-17', '2024-05-14', 'Ativo', 'Mark Ramsey', 'White despite eight avoid. Need since know street because.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (47, 'special', '2024-07-29', '2024-02-16', 'Inativo', 'Bryan Gonzalez', 'Majority through call he company. Claim help early budget among son. Girl make help western.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (48, 'style', '2024-02-11', '2024-04-18', 'Inativo', 'Allison Maldonado', 'Art me national. Above three air. Lawyer miss dinner available call.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (49, 'surface', '2024-10-03', '2024-06-01', 'Concluído', 'Jodi Taylor', 'Minute than sit wide natural increase different. Role sea grow reflect history turn.');
INSERT INTO dim_processo_seletivo (id_dim_processo_seletivo, nome, dt_inicio, dt_fim, status, criador, descricao) VALUES (50, 'run', '2024-11-24', '2024-02-05', 'Concluído', 'Christina Jensen', 'Main current particular if pay foot. Suddenly trade maybe outside arrive two.');

-- Inserções para a tabela dim_vaga
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (1, 'Research officer, political party', 8, 'Provide serve international deal defense green night money agree great loss.', 'Aberta', 'Brianbury', 'Christopher Carter');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (2, 'Social research officer, government', 9, 'Practice hear cup after director work.', 'Aberta', 'North Joseph', 'Susan Davis');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (3, 'Telecommunications researcher', 2, 'Change charge TV field foot before relate gas usually among street machine water page.', 'Fechada', 'Lake Justinside', 'Tracy Irwin');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (4, 'Sports administrator', 9, 'Third why decision public behavior clear fire allow money.', 'Fechada', 'New Margaret', 'Tammy Williams');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (5, 'Regulatory affairs officer', 7, 'See air majority sign national pay.', 'Aberta', 'New Lonnieview', 'Amy Gray');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (6, 'Education officer, museum', 8, 'Ever weight movie move smile unit much guy return remain long.', 'Em andamento', 'Lake Lisa', 'Kyle Reyes');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (7, 'Site engineer', 1, 'Occur with analysis community born raise fill impact soon.', 'Aberta', 'Joshuabury', 'Carmen Harper');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (8, 'Contracting civil engineer', 2, 'Century lot debate hair least act manager born fight else yourself on.', 'Fechada', 'New Jacob', 'Jonathan Sullivan');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (9, 'Therapist, speech and language', 6, 'Away may focus impact machine responsibility fear.', 'Aberta', 'East Angelaland', 'Nathan Clark');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (10, 'Regulatory affairs officer', 3, 'Hair interesting generation allow word cell individual.', 'Em andamento', 'Dawnville', 'Jason Blair');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (11, 'Tour manager', 2, 'Wall million town move politics rather guy.', 'Fechada', 'Baxterberg', 'Carlos Lee');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (12, 'Tax inspector', 4, 'Old partner program father at list.', 'Fechada', 'Hardingberg', 'Frank Cook');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (13, 'Training and development officer', 9, 'Because film still building run different law tree different if protect rich.', 'Aberta', 'West Meaganborough', 'Elizabeth Gilbert');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (14, 'Media planner', 1, 'Society relate against tend suggest outside pretty.', 'Fechada', 'New Frankbury', 'Derrick Walker');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (15, 'Engineer, structural', 10, 'Attorney water painting front news else general she.', 'Em andamento', 'East John', 'Gary Williams');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (16, 'Producer, television/film/video', 6, 'Summer room paper help where figure account simply recent fall specific system social.', 'Em andamento', 'Lisaburgh', 'Scott Ross Jr.');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (17, 'Chartered loss adjuster', 10, 'See generation family notice board blue.', 'Em andamento', 'Port Danny', 'Timothy Edwards');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (18, 'Health and safety adviser', 8, 'Less up history floor hand prepare order.', 'Aberta', 'Port Michael', 'Sandra Brown');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (19, 'Amenity horticulturist', 10, 'Quality right agent shoulder important positive most both appear minute experience.', 'Em andamento', 'West Tasha', 'Kerri Becker');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (20, 'Town planner', 9, 'Instead increase decision suffer able cost must school.', 'Fechada', 'West Joshuaburgh', 'Caleb Ellis');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (21, 'Further education lecturer', 1, 'Husband between direction knowledge those shake who leader.', 'Fechada', 'Lake Sara', 'Kimberly Wong');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (22, 'Operational researcher', 2, 'West staff economy involve answer oil everyone hospital almost down house.', 'Fechada', 'South David', 'Steven Wright');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (23, 'Arts administrator', 2, 'Program man look catch prepare science want.', 'Fechada', 'Smithborough', 'Christine Tucker');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (24, 'Print production planner', 1, 'Simple protect point modern time off.', 'Aberta', 'Josephville', 'Joshua Carrillo');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (25, 'Teacher, special educational needs', 7, 'Police machine able look ability sign.', 'Fechada', 'Port Jeremyton', 'Candice Morris');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (26, 'Astronomer', 9, 'Blood woman answer class truth avoid win figure role foot movement sister school.', 'Em andamento', 'South Seanburgh', 'Jason Scott');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (27, 'Charity fundraiser', 8, 'For one hit blood may body manage describe security market big machine ground.', 'Fechada', 'Smithshire', 'Andrew Blackburn');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (28, 'Radiation protection practitioner', 3, 'Produce administration tree some into clear marriage poor book discuss short.', 'Aberta', 'North Jorge', 'Michael West');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (29, 'Social researcher', 8, 'Owner pay reason price maintain learn.', 'Em andamento', 'Joelmouth', 'Jamie Fisher');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (30, 'Patent examiner', 2, 'Not seek lay news crime listen then adult.', 'Em andamento', 'Hickstown', 'Michael Smith');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (31, 'Animal technologist', 7, 'Explain produce Mr tree you plan sea loss painting discussion.', 'Aberta', 'Walshport', 'Marie Moore');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (32, 'Engineer, communications', 5, 'Development local west purpose room nor must.', 'Aberta', 'Jacquelineberg', 'Andres Perkins');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (33, 'Financial trader', 4, 'By huge enough financial watch cup system standard.', 'Fechada', 'Ashleyview', 'Gina Strickland');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (34, 'Engineer, aeronautical', 10, 'Already throughout here respond send too effect.', 'Fechada', 'Randolphbury', 'Nathaniel Turner');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (35, 'Chief Operating Officer', 3, 'Thus plan toward character answer stage notice national worry short.', 'Em andamento', 'Jeffreychester', 'Paul Woods');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (36, 'Teaching laboratory technician', 9, 'Wide American nature big number industry father her TV take.', 'Aberta', 'South Andrea', 'Nicole Jordan');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (37, 'Operational researcher', 8, 'Person lose sound real today hope save account challenge.', 'Aberta', 'Christineport', 'Daniel Williams');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (38, 'Tax inspector', 8, 'Issue business look lose not tend view event occur eight almost year.', 'Fechada', 'Kevinbury', 'Ms. Sierra Wheeler');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (39, 'Embryologist, clinical', 4, 'Send safe black within prepare capital road executive girl with remain.', 'Fechada', 'North Leahmouth', 'Rachel Green');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (40, 'Museum/gallery exhibitions officer', 8, 'Item sometimes want employee section example practice base.', 'Aberta', 'Williamsfurt', 'Matthew Watkins');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (41, 'Farm manager', 7, 'Value size Congress southern figure reality trial peace present.', 'Em andamento', 'Tarafurt', 'Stacey Salazar');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (42, 'Accounting technician', 4, 'Visit bad so both whose it.', 'Aberta', 'Nataliemouth', 'Laura Tyler');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (43, 'Water quality scientist', 4, 'Score although identify career own main field both son recently rise.', 'Em andamento', 'South Jim', 'Danny Marshall');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (44, 'Call centre manager', 9, 'Nor all agent rise successful fish seven film.', 'Aberta', 'Daniellefort', 'Michael Lee');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (45, 'Surveyor, rural practice', 5, 'American trip church piece debate left yet environmental leader.', 'Fechada', 'Denisemouth', 'Sean Wright');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (46, 'Surveyor, building control', 6, 'Air section since bit bit sometimes garden able culture force report local.', 'Aberta', 'Reyesfurt', 'Barbara Mcguire');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (47, 'Arboriculturist', 7, 'Program leader candidate product understand this growth leave others.', 'Fechada', 'Ballardfort', 'Kelly Hendrix');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (48, 'Chiropodist', 5, 'Father hot network since next challenge modern old.', 'Aberta', 'Port Sandramouth', 'Melissa Johnson');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (49, 'Warden/ranger', 9, 'Fact gun information own see lose ago actually choose political lose institution.', 'Em andamento', 'Butlerborough', 'Devin Daniels');
INSERT INTO dim_vaga (id_dim_vaga, titulo, nr_posicoes, requisitos, status, localizacao, responsavel) VALUES (50, 'Scientist, marine', 9, 'Situation bar clearly much accept bag capital.', 'Em andamento', 'East Deborah', 'Kenneth Graves');

