name: Deploy to AKS Cluster

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: pixelCluster
          resource-group: gr-pixel-containers
      
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          images: |
            springapppixel.azurecr.io/backend:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret
          namespace: ingress-basic
