name: Deploy to AKS Cluster

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build, docker] # Garante dependência
    if: github.ref == 'refs/heads/main' && success() # Apenas na main e se todos os jobs anteriores tiverem sucesso
    steps:
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: pixelCluster
          resource-group: gr-pixel-containers
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          images: |
            springapppixel.azurecr.io/backend:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret
          namespace: ingress-basic
